# Generated by Django 6.1 on 2026-09-11 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('competition', 'Competition'), ('award', 'Award'), ('certification', 'Certification'), ('academic', 'Academic')], default='award', max_length=20)),
            ],
        ),
    ]
