# Generated by Django 6.1 on 2026-09-11 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='date_awarded',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
