# Generated by Django 6.1 on 2026-09-20 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_achievement_date_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 20, 2, 54, 26, 319009, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
